// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master-data-service.proto

package master_data_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customername         string   `protobuf:"bytes,2,opt,name=customername,proto3" json:"customername,omitempty"`
	Customeremail        string   `protobuf:"bytes,3,opt,name=customeremail,proto3" json:"customeremail,omitempty"`
	Customerphone        string   `protobuf:"bytes,4,opt,name=customerphone,proto3" json:"customerphone,omitempty"`
	Customeraddress      string   `protobuf:"bytes,5,opt,name=customeraddress,proto3" json:"customeraddress,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e48557cb742acd00, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetCustomername() string {
	if m != nil {
		return m.Customername
	}
	return ""
}

func (m *Customer) GetCustomeremail() string {
	if m != nil {
		return m.Customeremail
	}
	return ""
}

func (m *Customer) GetCustomerphone() string {
	if m != nil {
		return m.Customerphone
	}
	return ""
}

func (m *Customer) GetCustomeraddress() string {
	if m != nil {
		return m.Customeraddress
	}
	return ""
}

func (m *Customer) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetCustomerDataRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Collection           string   `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerDataRequest) Reset()         { *m = GetCustomerDataRequest{} }
func (m *GetCustomerDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerDataRequest) ProtoMessage()    {}
func (*GetCustomerDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e48557cb742acd00, []int{1}
}

func (m *GetCustomerDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerDataRequest.Unmarshal(m, b)
}
func (m *GetCustomerDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerDataRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerDataRequest.Merge(m, src)
}
func (m *GetCustomerDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerDataRequest.Size(m)
}
func (m *GetCustomerDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerDataRequest proto.InternalMessageInfo

func (m *GetCustomerDataRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetCustomerDataRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetCustomerDataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetCustomerDataRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

type GetCustomerDataResponse struct {
	Api                  string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool        `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Token                string      `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Customer             []*Customer `protobuf:"bytes,5,rep,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCustomerDataResponse) Reset()         { *m = GetCustomerDataResponse{} }
func (m *GetCustomerDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerDataResponse) ProtoMessage()    {}
func (*GetCustomerDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e48557cb742acd00, []int{2}
}

func (m *GetCustomerDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerDataResponse.Unmarshal(m, b)
}
func (m *GetCustomerDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerDataResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerDataResponse.Merge(m, src)
}
func (m *GetCustomerDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerDataResponse.Size(m)
}
func (m *GetCustomerDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerDataResponse proto.InternalMessageInfo

func (m *GetCustomerDataResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetCustomerDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCustomerDataResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *GetCustomerDataResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetCustomerDataResponse) GetCustomer() []*Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func init() {
	proto.RegisterType((*Customer)(nil), "Customer")
	proto.RegisterType((*GetCustomerDataRequest)(nil), "GetCustomerDataRequest")
	proto.RegisterType((*GetCustomerDataResponse)(nil), "GetCustomerDataResponse")
}

func init() { proto.RegisterFile("master-data-service.proto", fileDescriptor_e48557cb742acd00) }

var fileDescriptor_e48557cb742acd00 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0xe9, 0xd7, 0x7e, 0xed, 0xf5, 0xa7, 0x3a, 0x48, 0x3b, 0x16, 0x91, 0x1a, 0x54, 0x8a,
	0xd8, 0x04, 0xeb, 0xce, 0xad, 0x82, 0x2b, 0x37, 0xf1, 0x09, 0xc6, 0xe4, 0x12, 0x83, 0x49, 0x26,
	0x9d, 0x99, 0x04, 0xdc, 0xba, 0xf1, 0x01, 0xdc, 0xf8, 0x50, 0xee, 0x7c, 0x05, 0x1f, 0x44, 0x32,
	0xc9, 0x48, 0x5b, 0xeb, 0xee, 0x9e, 0x73, 0x0f, 0x9c, 0x73, 0x2e, 0x17, 0xf6, 0x53, 0x26, 0x15,
	0x8a, 0x69, 0xc8, 0x14, 0x9b, 0x4a, 0x14, 0x65, 0x1c, 0xa0, 0x9b, 0x0b, 0xae, 0xf8, 0xe8, 0x20,
	0xe2, 0x3c, 0x4a, 0xd0, 0x63, 0x79, 0xec, 0xb1, 0x2c, 0xe3, 0x8a, 0xa9, 0x98, 0x67, 0xb2, 0xde,
	0x3a, 0x1f, 0x16, 0x74, 0xaf, 0x0b, 0xa9, 0x78, 0x8a, 0x82, 0x6c, 0x83, 0x1d, 0x87, 0xd4, 0x1a,
	0x5b, 0x93, 0x9e, 0x6f, 0xc7, 0x21, 0x71, 0x60, 0x33, 0x68, 0x76, 0x19, 0x4b, 0x91, 0xda, 0x7a,
	0xb3, 0xc4, 0x91, 0x63, 0xd8, 0x32, 0x18, 0x53, 0x16, 0x27, 0xb4, 0xa5, 0x45, 0xcb, 0xe4, 0xa2,
	0x2a, 0x7f, 0xe4, 0x19, 0xd2, 0x7f, 0xcb, 0x2a, 0x4d, 0x92, 0x09, 0xf4, 0x0d, 0xc1, 0xc2, 0x50,
	0xa0, 0x94, 0xb4, 0xad, 0x75, 0xab, 0x34, 0x19, 0x40, 0x47, 0x2a, 0xa6, 0x0a, 0x49, 0x3b, 0x5a,
	0xd0, 0x20, 0xa7, 0x84, 0xc1, 0x2d, 0x2a, 0x53, 0xe8, 0x86, 0x29, 0xe6, 0xe3, 0xbc, 0x40, 0xa9,
	0xc8, 0x0e, 0xb4, 0x58, 0x1e, 0x37, 0xe5, 0xaa, 0x91, 0xec, 0x41, 0x7b, 0x5e, 0xa0, 0x78, 0x6e,
	0x6a, 0xd5, 0xa0, 0x62, 0x4b, 0x96, 0x14, 0xd8, 0xf4, 0xa8, 0x01, 0x39, 0x04, 0x08, 0x78, 0x92,
	0x60, 0x50, 0xdd, 0xae, 0x09, 0xbf, 0xc0, 0x38, 0xef, 0x16, 0x0c, 0x7f, 0x19, 0xcb, 0x9c, 0x67,
	0x12, 0xd7, 0x38, 0x53, 0xf8, 0x9f, 0xa2, 0x94, 0x2c, 0x32, 0x27, 0x35, 0xb0, 0x72, 0x47, 0x21,
	0xb8, 0xd0, 0xee, 0x5d, 0xbf, 0x06, 0x15, 0xab, 0xf8, 0x13, 0x1a, 0xe3, 0x1a, 0x90, 0x13, 0xe8,
	0x9a, 0xb3, 0xd0, 0xf6, 0xb8, 0x35, 0xd9, 0x98, 0xf5, 0x5c, 0x13, 0xc0, 0xff, 0x59, 0xcd, 0x5e,
	0x2d, 0xd8, 0xbd, 0xd3, 0xdf, 0x51, 0xa5, 0xba, 0xaf, 0x7f, 0x83, 0x08, 0xe8, 0xaf, 0xe4, 0x25,
	0x43, 0x77, 0xfd, 0xe9, 0x46, 0xd4, 0xfd, 0xa3, 0x9a, 0x73, 0xfe, 0xf2, 0xf9, 0xf5, 0x66, 0x9f,
	0x3a, 0x47, 0x5e, 0x79, 0xe1, 0x2d, 0xbc, 0xa0, 0x17, 0xa1, 0x9a, 0x9a, 0x04, 0x9a, 0xb9, 0xb2,
	0xce, 0x1e, 0x3a, 0xfa, 0xe5, 0x2e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x60, 0xe0, 0x2d,
	0xad, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterDataServiceClient is the client API for MasterDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterDataServiceClient interface {
	GetCustomerData(ctx context.Context, in *GetCustomerDataRequest, opts ...grpc.CallOption) (*GetCustomerDataResponse, error)
}

type masterDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMasterDataServiceClient(cc *grpc.ClientConn) MasterDataServiceClient {
	return &masterDataServiceClient{cc}
}

func (c *masterDataServiceClient) GetCustomerData(ctx context.Context, in *GetCustomerDataRequest, opts ...grpc.CallOption) (*GetCustomerDataResponse, error) {
	out := new(GetCustomerDataResponse)
	err := c.cc.Invoke(ctx, "/MasterDataService/GetCustomerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterDataServiceServer is the server API for MasterDataService service.
type MasterDataServiceServer interface {
	GetCustomerData(context.Context, *GetCustomerDataRequest) (*GetCustomerDataResponse, error)
}

// UnimplementedMasterDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMasterDataServiceServer struct {
}

func (*UnimplementedMasterDataServiceServer) GetCustomerData(ctx context.Context, req *GetCustomerDataRequest) (*GetCustomerDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerData not implemented")
}

func RegisterMasterDataServiceServer(s *grpc.Server, srv MasterDataServiceServer) {
	s.RegisterService(&_MasterDataService_serviceDesc, srv)
}

func _MasterDataService_GetCustomerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterDataServiceServer).GetCustomerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MasterDataService/GetCustomerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterDataServiceServer).GetCustomerData(ctx, req.(*GetCustomerDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MasterDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MasterDataService",
	HandlerType: (*MasterDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerData",
			Handler:    _MasterDataService_GetCustomerData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master-data-service.proto",
}
